### ISSUE TITLE
crash after start 

### ISSUE THREAD

**Issue by jfima** [xtr4nge/FruityShell#1]
same error on my raspberry pi, but maybe something wrong witch my python configuration. 
this is my kali 2.0 vbox shell error:

``` bash
root@kali:~/FruityShell# ./FruityShell.py 
| __| _ _  _(_) |_ _  \ \    / (_) __(_) / __| |_  ___| | |
| _| '_| || | |  _| || \ \/\/ /| | _|| | \__ \ ' \/ -_) | |
|_||_|  \_,_|_|\__|\_, |\_/\_/ |_|_| |_| |___/_||_\___|_|_|
                   |__/
                                               version 1.0
Site: http://www.fruitywifi.com
Twitter: @fruitywifi @xtr4nge

[+] Session established. Have fun ;)

[*] FruityShell v1.0

Traceback (most recent call last):
  File "./FruityShell.py", line 329, in <module>
    for line in out.json():
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


```

about pip and python

``` bash
root@kali:~/FruityShell# pip -V
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
root@kali:~/FruityShell# python -V
python 2.7.9
```

**Comment by xtr4nge** [comment]
Hi jfima,
Please ensure that you have the latest version (requests):

`pip install --upgrade requests`

Do you have modules installed?

Try to pull the modules manually using the API:

`http://{IP}:8000/modules/api/includes/ws_action.php?token={TOKEN}&api=/module`

(replace {IP} and {TOKEN} with your details)

What is the output?

Please let me know
regards,

**Comment by jfima** [comment]
as you can see

``` bash

root@kali:~/FruityShell# pip install --upgrade requests
Downloading/unpacking requests from https://pypi.python.org/packages/2.7/r/requests/requests-2.8.1-py2.py3-none-any.whl#md5=46f1d621daa3ab38958a42f51478b1ee
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB): 497kB downloaded
Installing collected packages: requests
  Found existing installation: requests 2.7.0
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed requests
Cleaning up...

```

same error!

``` txt
[+] Session established. Have fun ;)

[*] FruityShell v1.0

Traceback (most recent call last):
  File "./FruityShell.py", line 329, in <module>
    for line in out.json():
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

http://192.168.7.146:8000/modules/api/includes/ws_action.php?token=e5dab9a69988dd65e578041416773149ea57a054&api=/module

``` bash

404 Not Found
nginx/1.6.2

```

web interface & modules worked fine
![image](https://cloud.githubusercontent.com/assets/4493706/10708140/de044ef8-7a06-11e5-9c79-77d09d0cf9ff.png)

**Comment by xtr4nge** [comment]
Hi jfima,
It looks like you don't have the API module installed.
Without the API module, FruityShell neither FruityDisplay will work.

Go to the modules page from FruityWiFi web-interface, and install the API module.

REF: https://github.com/xtr4nge/module_api

regards,
